export const orderList = [{
        "ID": 1,
        "OrderNum": "491134783130二次保密",
        "OrderFrom": "再出发（惠和）",
        "HotelName": "青岛崂山湾酒店",
        "CheckInDate": "2017-04-13",
        "CheckOutDate": "2017-04-15",
        "BookDate": "2017-04-11 ",
        "CustomerName": "王磊",
        "IsScreenshot": true,
        "IsSubmit": true,
        "IsRemit": true,
        "IsEdit": false,
        "IsAudit": true,
        "SubmitterName": "李磊",
    },
    {
        "ID": 2,
        "OrderNum": "491134783131二次保密",
        "OrderFrom": "携程",
        "HotelName": "青岛崂山湾酒店",
        "CheckInDate": "2017-04-18",
        "CheckOutDate": "2017-04-20",
        "BookDate": "2017-04-11 ",
        "CustomerName": "王磊",
        "IsScreenshot": true,
        "IsSubmit": true,
        "IsRemit": true,
        "IsEdit": false,
        "IsAudit": false,
        "SubmitterName": "李磊1",
    },
    {
        "ID": 3,
        "OrderNum": "3552726220 团队房 统一打款 二次保密",
        "OrderFrom": "艺龙",
        "HotelName": "青岛远雄悦来酒店",
        "CheckInDate": "2017-04-14",
        "CheckOutDate": "2017-04-15",
        "BookDate": "2017-04-11 ",
        "CustomerName": "王磊",
        "IsScreenshot": true,
        "IsSubmit": false,
        "IsRemit": false,
        "IsEdit": true,
        "IsAudit": false,
        "SubmitterName": "李磊1",
    }, {
        "ID": 4,
        "OrderNum": "微信--李朝宇 谭聪祥 胡总朋友 未支付",
        "OrderFrom": "飞猪",
        "HotelName": "北京燕山大酒店",
        "CheckInDate": "2017-04-13",
        "CheckOutDate": "2017-04-17",
        "BookDate": "2017-04-11 ",
        "CustomerName": "王磊",
        "IsScreenshot": true,
        "IsSubmit": true,
        "IsRemit": false,
        "IsEdit": true,
        "IsAudit": false,
        "SubmitterName": "李磊1",
    }, {
        "ID": 5,
        "OrderNum": "491134689743预付款 不打款",
        "OrderFrom": "携程",
        "HotelName": "青岛途家斯维登度假公寓（万象城店）",
        "CheckInDate": "2017-04-13",
        "CheckOutDate": "2017-04-19",
        "BookDate": "2017-04-11 ",
        "CustomerName": "王磊1",
        "IsScreenshot": false,
        "IsSubmit": false,
        "IsRemit": false,
        "IsEdit": false,
        "IsAudit": false,
        "SubmitterName": "李磊",
    }, {
        "ID": 6,
        "OrderNum": "9801911710297593",
        "OrderFrom": "携程",
        "HotelName": "青岛崂山湾酒店",
        "CheckInDate": "2017-04-13",
        "CheckOutDate": "2017-04-15",
        "BookDate": "2017-04-11 ",
        "CustomerName": "王磊1",
        "IsScreenshot": false,
        "IsSubmit": true,
        "IsRemit": false,
        "IsEdit": true,
        "IsAudit": false,
        "SubmitterName": "李磊",
    }
]
